# Generated by Django 3.0.4 on 2020-03-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=40)),
                ('ingredient_category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipe_builder.Ingredient_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipe_builder.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=100)),
                ('receipt', models.TextField(blank=True)),
                ('dish_category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipe_builder.Dish_Category')),
                ('ingredient_id', models.ManyToManyField(to='recipe_builder.Dish_Ingredient')),
            ],
        ),
    ]
