# Generated by Django 3.0.4 on 2020-03-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='id',
            new_name='dish_id',
        ),
        migrations.RenameField(
            model_name='dish_category',
            old_name='id',
            new_name='dish_category_id',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='id',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='ingredient_category',
            old_name='id',
            new_name='ingredient_category_id',
        ),
    ]
