# Generated by Django 3.0.4 on 2020-03-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_builder', '0002_auto_20200323_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='receipt',
            new_name='dish_description',
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True),
        ),
    ]
